run:
  deadline: 1m
  skip-files:
    - '(.+)_test\.go'

linters:
  disable-all: false
  enable:
    - dogsled
    - dupl
    - whitespace
    - wsl
  disable:
    - lll
  presets:
    - bugs
    - unused
  fast: false
